USE Diplomatic_Data;

INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ae', 'Madinat Zayid', 23.6522, 53.6536);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ae', 'Abu Dhabi', 24.4781, 54.3686);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ae', 'Al Fujayrah', 25.1308, 56.3347);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ae', 'Dubai', 25.2697, 55.3094);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ae', 'Umm Al Qaywayn', 25.5653, 55.5533);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ae', 'Al `Ayn', 24.2075, 55.7447);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ae', 'Ra`s Al Khaymah', 25.7915, 55.9428);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ae', '`Ajman', 25.3994, 55.4797);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ae', 'Sharjah', 25.3575, 55.3919);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('au', 'Toowoomba', -27.5667, 151.95);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('au', 'Adelaide', -34.9289, 138.601);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('au', 'Caloundra', -26.7986, 153.129);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('au', 'Launceston', -41.4419, 147.145);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('au', 'Bunbury', -33.3333, 115.633);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('au', 'Bendigo', -36.75, 144.267);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('au', 'Mackay', -21.1411, 149.186);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('au', 'Perth', -31.9522, 115.859);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('au', 'Leopold', -38.1892, 144.464);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('au', 'Concord', -33.8444, 151.09);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('au', 'Newcastle', -32.9167, 151.75);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('au', 'Campbelltown', -34.0733, 150.826);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('au', 'Ipswich', -27.6167, 152.767);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('au', 'Rockhampton', -23.375, 150.512);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('au', 'Maitland', -32.7167, 151.55);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('au', 'Canberra', -35.2931, 149.127);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('au', 'Darwin', -12.4381, 130.841);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('au', 'Sydney', -33.865, 151.209);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('au', 'Brisbane', -27.4678, 153.028);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('au', 'Geelong', -38.15, 144.35);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('be', 'Ieper', 50.85, 2.8833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('be', 'Roeselare', 50.9447, 3.1233);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('be', 'Hasselt', 50.9304, 5.3383);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('be', 'Mons', 50.455, 3.952);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('be', 'La Louviere', 50.4778, 4.1881);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('be', 'Dendermonde', 51.0167, 4.1);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('be', 'Mechelen', 51.0281, 4.4803);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('be', 'Sint-Niklaas', 51.1644, 4.1392);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('be', 'Oudenaarde', 50.85, 3.6);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('be', 'Charleroi', 50.4167, 4.4442);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('be', 'Bruges', 51.2089, 3.2242);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('be', 'Anderlecht', 50.8392, 4.3297);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('be', 'Antwerp', 51.2211, 4.3997);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('be', 'Geraardsbergen', 50.7667, 3.8667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('be', 'Brussels', 50.8467, 4.3517);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('be', 'Halle', 50.7361, 4.2372);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('be', 'Schaarbeek', 50.8675, 4.3736);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('be', 'Namur', 50.4667, 4.8667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('be', 'Gent', 51.0536, 3.7253);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('be', 'Vilvoorde', 50.9281, 4.4245);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('bh', 'Madinat `Isa', 26.1736, 50.5478);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('bh', 'Manama', 26.2167, 50.5831);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('bh', 'Al Muharraq', 26.25, 50.6167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('bh', 'Madinat Hamad', 26.1128, 50.5139);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('bm', 'Hamilton', 32.2942, -64.7839);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('br', 'Rio De Janeiro', -22.9083, -43.1964);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('br', 'Belo Horizonte', -19.8917, -43.9478);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('br', 'Vitoria', -20.324, -40.366);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('br', 'Iguacu', -22.74, -43.47);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('br', 'Jaboatao', -8.1803, -35.0014);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('br', 'Belem', -1.4558, -48.5039);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('br', 'Sao Paulo', -23.5504, -46.6339);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('br', 'Maceio', -9.6658, -35.735);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('br', 'Joinvile', -26.32, -48.8399);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('br', 'Recife', -8.0539, -34.8808);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('br', 'Novo Hamburgo', -29.7096, -51.14);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('br', 'Teresina', -5.0949, -42.8042);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('br', 'Curitiba', -25.4297, -49.2719);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('br', 'Joao Pessoa', -7.0833, -34.8333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('br', 'Sao Bernardo Do Campo', -23.6939, -46.565);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('br', 'Olinda', -8.0, -34.85);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('br', 'Guarulhos', -23.4667, -46.5333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('br', 'Santo Andre', -23.6572, -46.5333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('br', 'Fortaleza', -3.7275, -38.5275);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('br', 'Natal', -5.795, -35.2089);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ca', 'Richmond', 49.1667, -123.133);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ca', 'Vancouver', 49.25, -123.1);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ca', 'Montreal', 45.5089, -73.5617);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ca', 'Oakville', 43.45, -79.6833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ca', 'Mississauga', 43.6, -79.65);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ca', 'Ottawa', 45.4247, -75.695);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ca', 'Niagara Falls', 43.06, -79.1067);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ca', 'Richmond Hill', 43.8667, -79.4333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ca', 'Vaughan', 43.8333, -79.5);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ca', 'London', 42.9836, -81.2497);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ca', 'Laval', 45.5833, -73.75);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ca', 'Windsor', 42.2833, -83.0);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ca', 'Winnipeg', 49.8844, -97.1464);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ca', 'Longueuil', 45.5333, -73.5167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ca', 'Toronto', 43.7417, -79.3733);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ca', 'Calgary', 51.05, -114.067);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ca', 'Victoria', 48.4283, -123.365);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ca', 'Hamilton', 43.2567, -79.8692);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ca', 'Edmonton', 53.5344, -113.49);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ca', 'Burnaby', 49.2667, -122.967);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ch', 'Geneva', 46.2, 6.15);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ch', 'Neuchatel', 46.9903, 6.9306);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ch', 'Basel', 47.5606, 7.5906);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ch', 'Meyrin', 46.2322, 6.0791);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ch', 'Carouge', 46.1817, 6.1404);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ch', 'Vernier', 46.2, 6.1);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ch', 'Reinach', 47.4936, 7.5908);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ch', 'Lucerne', 47.0523, 8.3059);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ch', 'Schaffhausen', 47.6965, 8.6339);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ch', 'Dietikon', 47.4056, 8.4039);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ch', 'Fribourg', 46.8, 7.15);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ch', 'Renens', 46.5353, 6.5897);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ch', 'Zurich', 47.3786, 8.54);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ch', 'Zug', 47.1692, 8.5164);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ch', 'Lausanne', 46.5333, 6.6333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ch', 'Opfikon', 47.4331, 8.5719);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ch', 'Bellinzona', 46.1956, 9.0238);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ch', 'Allschwil', 47.5508, 7.5358);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ch', 'Bern', 46.948, 7.4474);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ch', 'Aarau', 47.3923, 8.0446);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('cn', 'Beijing', 39.905, 116.391);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('cn', 'Wuhan', 30.5872, 114.288);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('cn', 'Baoding', 38.8671, 115.484);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('cn', 'Ningbo', 29.875, 121.549);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('cn', 'Hefei', 31.8639, 117.281);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('cn', 'Nanjing', 32.05, 118.767);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('cn', 'Linyi', 35.0606, 118.342);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('cn', 'Chengdu', 30.6636, 104.067);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('cn', 'Tongshan', 34.261, 117.186);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('cn', 'Changchun', 43.9, 125.2);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('cn', 'Fuyang', 32.8986, 115.804);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('cn', 'Shanghai', 31.1667, 121.467);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('cn', 'Shijiazhuang', 38.0422, 114.509);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('cn', 'Chongqing', 29.55, 106.507);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('cn', 'Nanning', 22.8192, 108.315);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('cn', 'Nantong', 31.9829, 120.887);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('cn', 'Foshan', 23.0292, 113.106);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('cn', 'Ganzhou', 25.8292, 114.934);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('cn', 'Zhumadian', 32.9773, 114.025);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('cn', 'Jining', 35.4, 116.567);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('co', 'Monteria', 8.76, -75.8856);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('co', 'Popayan', 2.4411, -76.6061);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('co', 'Pasto', 1.2136, -77.2811);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('co', 'Barrancabermeja', 7.09, -73.85);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('co', 'Valledupar', 10.4603, -73.2597);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('co', 'Neiva', 2.9275, -75.2875);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('co', 'Manizales', 5.06, -75.52);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('co', 'Armenia', 4.5389, -75.6725);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('co', 'Pereira', 4.8104, -75.68);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('co', 'Bucaramanga', 7.1186, -73.1161);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('co', 'Villavicencio', 4.1425, -73.6294);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('co', 'Cali', 3.44, -76.5197);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('co', 'Bogota', 4.6126, -74.0705);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('co', 'Girardot', 4.31, -74.81);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('co', 'Cartago', 4.75, -75.91);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('co', 'Bello', 6.33, -75.57);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('co', 'Ibague', 4.4378, -75.2006);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('co', 'Cucuta', 7.9075, -72.5047);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('co', 'Tulua', 4.0904, -76.21);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('co', 'Medellin', 6.2447, -75.5748);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('de', 'Berlin', 52.5167, 13.3833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('de', 'Bielefeld', 52.0167, 8.5333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('de', 'Essen', 51.4508, 7.0131);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('de', 'Munich', 48.1372, 11.5755);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('de', 'Wiesbaden', 50.0825, 8.24);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('de', 'Chemnitz', 50.8333, 12.9167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('de', 'Karlsruhe', 49.0167, 8.4);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('de', 'Bremen', 53.1153, 8.7975);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('de', 'Nuremberg', 49.4528, 11.0778);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('de', 'Cologne', 50.9422, 6.9578);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('de', 'Munster', 51.9625, 7.6256);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('de', 'Aachen', 50.7762, 6.0838);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('de', 'Augsburg', 48.3717, 10.8983);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('de', 'Stuttgart', 48.7761, 9.1775);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('de', 'Hannover', 52.3744, 9.7386);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('de', 'Dortmund', 51.5139, 7.4653);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('de', 'Monchengladbach', 51.2, 6.4333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('de', 'Hamburg', 53.55, 10.0);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('de', 'Duisburg', 51.4322, 6.7611);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('de', 'Mannheim', 49.4878, 8.4661);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('do', 'Higuey', 18.616, -68.708);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('do', 'Cotui', 19.06, -70.15);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('do', 'Mao', 19.552, -71.075);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('do', 'Santo Domingo Este', 18.4885, -69.8571);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('do', 'San Juan', 18.807, -71.229);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('do', 'Santiago', 19.5, -70.67);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('do', 'Hato Mayor', 18.764, -69.257);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('do', 'Dajabon', 19.5667, -71.71);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('do', 'Azua', 18.454, -70.729);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('do', 'Bonao', 18.942, -70.409);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('do', 'La Romana', 18.417, -68.9666);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('do', 'Pantanal', 18.5103, -68.3694);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('do', 'Samana', 19.212, -69.332);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('do', 'San Cristobal', 18.416, -70.109);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('do', 'San Francisco De Macoris', 19.3, -70.25);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('do', 'Nagua', 19.376, -69.847);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('do', 'San Pedro De Macoris', 18.4504, -69.3);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('do', 'El Seibo', 18.764, -69.035);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('do', 'Barahona', 18.2079, -71.0996);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('do', 'Bani', 18.28, -70.331);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('eg', 'Tanta', 30.7833, 31.0);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('eg', 'Suhaj', 26.5606, 31.6917);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('eg', 'Luxor', 25.6969, 32.6422);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('eg', 'Alexandria', 31.2, 29.9167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('eg', 'Al `Arish', 31.1249, 33.8006);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('eg', 'Ismailia', 30.5833, 32.2667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('eg', 'Aswan', 24.0889, 32.8997);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('eg', 'Giza', 29.987, 31.2118);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('eg', 'Qina', 26.1667, 32.7167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('eg', 'Al Mahallah Al Kubra', 30.9667, 31.1667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('eg', 'Shubra Al Khaymah', 30.1286, 31.2422);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('eg', 'Mallawi', 27.7306, 30.8425);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('eg', 'Al Fayyum', 29.3, 30.8333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('eg', 'Shibin Al Kawm', 30.592, 30.9);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('eg', 'Kafr Ad Dawwar', 31.1417, 30.1272);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('eg', 'Kafr Ash Shaykh', 31.1, 30.95);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('eg', 'Cairo', 30.0561, 31.2394);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('eg', 'Port Said', 31.25, 32.2833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('eg', 'Az Zaqaziq', 30.5667, 31.5);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('eg', 'Madinat As Sadis Min Uktubar', 29.9361, 30.9269);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('es', 'Sevilla', 37.3828, -5.9731);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('es', 'Albacete', 38.9956, -1.8558);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('es', 'Bilbao', 43.2622, -2.9533);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('es', 'Malaga', 36.7167, -4.4167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('es', 'Zaragoza', 41.6483, -0.883);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('es', 'Pamplona', 42.8167, -1.65);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('es', 'Badalona', 41.4333, 2.2333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('es', 'Almeria', 36.8333, -2.45);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('es', 'Santander', 43.4667, -3.8);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('es', 'Jerez De La Frontera', 36.7, -6.1167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('es', 'Valladolid', 41.652, -4.7286);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('es', 'A Coruna', 43.3713, -8.4188);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('es', 'Mataro', 41.54, 2.45);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('es', 'Murcia', 37.9866, -1.1415);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('es', 'Las Palmas', 28.1272, -15.4314);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('es', 'Barcelona', 41.3825, 2.1769);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('es', 'Madrid', 40.4189, -3.6919);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('es', 'Cartagena', 37.6, -0.9819);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('es', 'Vitoria-Gasteiz', 42.8467, -2.6731);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('es', 'Vigo', 42.2358, -8.7267);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('et', 'Jijiga', 9.35, 42.8);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('et', 'Hosa`ina', 7.5504, 37.85);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('et', 'Bahir Dar', 11.585, 37.39);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('et', 'Debre Zeyit', 8.75, 38.9833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('et', 'Dese', 11.1333, 39.6333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('et', 'Nek`emte', 9.0905, 36.53);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('et', 'Goba', 7.01, 39.97);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('et', 'Semera', 11.7956, 41.0086);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('et', 'Negele', 5.3166, 39.5833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('et', 'Giyon', 8.5304, 37.97);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('et', 'Nazret', 8.55, 39.27);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('et', 'Gode', 5.95, 43.45);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('et', 'Shashemene', 7.2004, 38.59);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('et', 'Debre Birhan', 9.6804, 39.53);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('et', 'Mekele', 13.4833, 39.4667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('et', 'Aksum', 14.1284, 38.7173);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('et', 'Gambela', 8.25, 34.5833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('et', 'Gonder', 12.6, 37.4667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('et', 'Harar', 9.32, 42.15);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('et', 'Asela', 7.95, 39.1167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fm', 'Colonia', 9.5144, 138.129);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fm', 'Weno', 7.4458, 151.85);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fm', 'Palikir', 6.9178, 158.185);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fm', 'Kolonia', 6.9639, 158.208);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fm', 'Tofol', 5.3261, 163.008);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fr', 'Clermont-Ferrand', 45.7831, 3.0824);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fr', 'Dijon', 47.3167, 5.0167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fr', 'Toulon', 43.1258, 5.9306);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fr', 'Nice', 43.7034, 7.2663);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fr', 'Limoges', 45.8353, 1.2625);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fr', 'Grenoble', 45.1715, 5.7224);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fr', 'Lyon', 45.76, 4.84);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fr', 'Mulhouse', 47.75, 7.34);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fr', 'Orleans', 47.9025, 1.909);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fr', 'Marseille', 43.2964, 5.37);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fr', 'Nancy', 48.6936, 6.1846);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fr', 'Toulouse', 43.6045, 1.444);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fr', 'Brest', 48.39, -4.49);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fr', 'Angers', 47.4736, -0.5542);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fr', 'Villeurbanne', 45.7667, 4.8803);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fr', 'Rouen', 49.4428, 1.0886);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fr', 'Lille', 50.6278, 3.0583);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fr', 'Aix-En-Provence', 43.5263, 5.4454);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fr', 'Reims', 49.2628, 4.0347);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('fr', 'Strasbourg', 48.5833, 7.7458);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gb', 'Bristol', 51.45, -2.5833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gb', 'London', 51.5072, -0.1275);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gb', 'Derby', 52.9167, -1.4667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gb', 'Leeds', 53.7997, -1.5492);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gb', 'Portsmouth', 50.8058, -1.0872);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gb', 'Glasgow', 55.8609, -4.2514);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gb', 'Southampton', 50.9, -1.4);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gb', 'Belfast', 54.5964, -5.93);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gb', 'Milton Keynes', 52.04, -0.76);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gb', 'Wolverhampton', 52.5833, -2.1333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gb', 'Manchester', 53.4794, -2.2453);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gb', 'Caerdydd', 51.4833, -3.1833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gb', 'Abertawe', 51.6167, -3.95);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gb', 'Liverpool', 53.4, -2.9833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gb', 'Luton', 51.8783, -0.4147);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gb', 'Aberdeen', 57.15, -2.11);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gb', 'Edinburgh', 55.953, -3.189);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gb', 'Birmingham', 52.48, -1.9025);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gb', 'Nottingham', 52.95, -1.15);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gb', 'Coventry', 52.4081, -1.5106);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gy', 'Linden', 6.0, -58.3);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gy', 'Fort Wellington', 6.3909, -57.6038);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gy', 'Georgetown', 6.7833, -58.1667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gy', 'Vreed-En-Hoop', 6.8, -58.1833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gy', 'Anna Regina', 7.25, -58.5167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gy', 'Mahdia', 5.2667, -59.15);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gy', 'Ituni', 5.5333, -58.25);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gy', 'Bartica', 6.4, -58.6167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gy', 'New Amsterdam', 6.25, -57.5167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gy', 'Lethem', 3.3833, -59.8);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gy', 'Princetown', 5.9, -57.17);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('gy', 'Mabaruma', 8.2, -59.7833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('hk', 'Hong Kong', 22.305, 114.185);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ie', 'Mullingar', 53.5333, -7.35);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ie', 'Kilkenny', 52.6477, -7.2561);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ie', 'Castlebar', 53.85, -9.3);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ie', 'Sligo', 54.2667, -8.4833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ie', 'Limerick', 52.6653, -8.6238);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ie', 'Swords', 53.4597, -6.2181);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ie', 'Dublin', 53.3425, -6.2658);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ie', 'Carrick On Shannon', 53.9469, -8.09);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ie', 'Tullamore', 53.2667, -7.5);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ie', 'Longford', 53.7333, -7.8);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ie', 'Drogheda', 53.7139, -6.3503);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ie', 'Tralee', 52.2675, -9.6962);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ie', 'Wexford', 52.3342, -6.4575);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ie', 'Dunleary', 53.3, -6.14);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ie', 'Nenagh', 52.8619, -8.1967);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ie', 'Naas', 53.2158, -6.6669);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ie', 'Port Laoise', 53.0309, -7.3008);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ie', 'Galway', 53.2729, -9.0418);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ie', 'Monaghan', 54.2479, -6.9708);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ie', 'Dun Dealgan', 54.009, -6.4049);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('in', 'Patna', 25.61, 85.1414);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('in', 'Delhi', 28.66, 77.23);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('in', 'Bangalore', 12.9699, 77.598);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('in', 'Hyderabad', 17.3667, 78.4667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('in', 'Vishakhapatnam', 17.7333, 83.3167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('in', 'Chinchvad', 18.6278, 73.8131);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('in', 'Indore', 22.7206, 75.8472);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('in', 'Jaipur', 26.9167, 75.8667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('in', 'Pune', 18.5196, 73.8553);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('in', 'Surat', 21.17, 72.83);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('in', 'Chennai', 13.0825, 80.275);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('in', 'Jamshedpur', 22.8, 86.1833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('in', 'Ludhiana', 30.9083, 75.8486);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('in', 'Ahmadabad', 23.03, 72.58);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('in', 'Faridabad', 28.4333, 77.3167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('in', 'Kalyan', 19.2502, 73.1602);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('in', 'Ghaziabad', 28.6667, 77.4167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('in', 'Bhopal', 23.25, 77.4167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('in', 'Agra', 27.18, 78.02);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('in', 'Vadodara', 22.3, 73.2);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ir', 'Zanjan', 36.6667, 48.4833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ir', 'Qom', 34.6461, 50.8789);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ir', 'Malard', 35.6658, 50.9767);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ir', 'Sarta', 36.5504, 53.1);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ir', 'Khorramabad', 33.4667, 48.35);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ir', 'Qazvin', 36.2688, 50.0041);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ir', 'Tehran', 35.7, 51.4167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ir', 'Rasht', 37.2833, 49.6);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ir', 'Ardabil', 38.25, 48.3);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ir', 'Sari', 36.5658, 53.0597);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ir', 'Zahedan', 29.4833, 60.8667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ir', 'Ahvaz', 31.3203, 48.6692);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ir', 'Gorgan', 36.83, 54.48);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ir', 'Eslamshahr', 35.5333, 51.2);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ir', 'Bandar `Abbas', 27.2, 56.25);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ir', 'Shahriar', 35.6597, 51.0592);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ir', 'Shiraz', 29.61, 52.5425);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ir', 'Kashan', 33.9833, 51.4333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ir', 'Mashhad', 36.3069, 59.6042);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ir', 'Kermanshah', 34.3167, 47.0686);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('it', 'Naples', 40.8333, 14.25);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('it', 'Foggia', 41.4584, 15.5519);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('it', 'Rome', 41.8931, 12.4828);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('it', 'Brescia', 45.5389, 10.2203);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('it', 'Bologna', 44.4939, 11.3428);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('it', 'Ravenna', 44.4178, 12.1994);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('it', 'Turin', 45.0667, 7.7);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('it', 'Florence', 43.7714, 11.2542);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('it', 'Prato', 43.8808, 11.0966);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('it', 'Reggio Di Calabria', 38.1144, 15.65);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('it', 'Ferrara', 44.8353, 11.6199);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('it', 'Parma', 44.8015, 10.328);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('it', 'Livorno', 43.55, 10.3167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('it', 'Venice', 45.4397, 12.3319);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('it', 'Bari', 41.1253, 16.8667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('it', 'Cagliari', 39.2224, 9.104);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('it', 'Genoa', 44.4072, 8.934);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('it', 'Rimini', 44.0594, 12.5683);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('it', 'Verona', 45.4386, 10.9928);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('it', 'Milan', 45.4669, 9.19);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('jp', 'Kagoshima', 31.58, 130.528);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('jp', 'Kawanakajima', 35.53, 139.705);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('jp', 'Saitama', 35.8617, 139.645);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('jp', 'Utsunomiya', 36.55, 139.883);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('jp', 'Kobe', 34.6913, 135.183);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('jp', 'Matsudo', 35.7878, 139.903);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('jp', 'Higashi-Osaka', 34.6794, 135.601);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('jp', 'Nishinomiya-Hama', 34.7333, 135.333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('jp', 'Ichikawa', 35.7219, 139.931);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('jp', 'Sapporo', 43.0621, 141.354);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('jp', 'Chiba', 35.6, 140.1);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('jp', 'Kawaguchi', 35.8078, 139.724);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('jp', 'Kitaku', 33.8704, 130.82);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('jp', 'Hamamatsu', 34.7167, 137.733);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('jp', 'Hiroshima', 34.3853, 132.455);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('jp', 'Kyoto', 35.0111, 135.767);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('jp', 'Matsuyama', 33.8333, 132.767);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('jp', 'Osaka', 34.6936, 135.502);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('jp', 'Sendai', 38.2683, 140.869);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('jp', 'Yokohama', 35.4333, 139.633);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ke', 'Mandera', 3.9167, 41.8333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ke', 'Thika', -1.0396, 37.09);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ke', 'Mumias', 0.3333, 34.4833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ke', 'Moyale', 3.527, 39.056);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ke', 'Mombasa', -4.05, 39.6667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ke', 'Kitui', -1.3667, 38.0167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ke', 'Marsabit', 2.3333, 37.9833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ke', 'Isiolo', 0.35, 37.5833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ke', 'Bungoma', 0.5666, 34.5666);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ke', 'Nairobi', -1.2864, 36.8172);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ke', 'Lodwar', 3.1167, 35.6);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ke', 'Kakamega', 0.2833, 34.75);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ke', 'Eldama Ravine', 0.0504, 35.72);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ke', 'Kisii', -0.6817, 34.7667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ke', 'Maralal', 1.1, 36.7);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ke', 'Wajir', 1.75, 40.0667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ke', 'Kisumu', -0.1, 34.75);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ke', 'Homa Bay', -0.5167, 34.45);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ke', 'Nakuru', -0.2833, 36.0667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ke', 'Eldoret', 0.5167, 35.2833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('kz', 'Taraz', 42.8833, 71.3667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('kz', 'Satbaev', 47.9, 67.5333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('kz', 'Qaskeleng', 43.1983, 76.6311);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('kz', 'Rudnyy', 52.9527, 63.13);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('kz', 'Kentau', 43.5169, 68.5044);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('kz', 'Taldyqorghan', 45.0167, 78.3667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('kz', 'Aqtobe', 50.3, 57.1667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('kz', 'Turkistan', 43.3, 68.2436);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('kz', 'Atyrau', 47.1167, 51.8833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('kz', 'Oral', 51.2333, 51.3667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('kz', 'Ekibastuz', 51.7298, 75.3266);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('kz', 'Zhezqazghan', 47.7833, 67.7);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('kz', 'Qaraghandy', 49.8, 73.1167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('kz', 'Balqash', 46.85, 75.0);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('kz', 'Aqsu', 52.0333, 76.9167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('kz', 'Kokshetau', 53.2824, 69.3969);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('kz', 'Oskemen', 49.95, 82.6167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('kz', 'Sarqan', 45.4203, 79.9149);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('kz', 'Nur-Sultan', 51.1333, 71.4333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('kz', 'Qostanay', 53.2144, 63.6246);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lb', 'Tripoli', 34.4333, 35.8333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lb', 'Baalbek', 34.0061, 36.2086);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lb', 'Nabatiye', 33.3833, 35.45);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lb', 'Tyre', 33.2667, 35.2);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lb', 'Baabda', 33.8333, 35.5333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lb', 'Jounie', 33.9697, 35.6156);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lb', 'Halba', 34.5428, 36.0797);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lb', 'El Qaa', 34.3436, 36.4756);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lb', 'Zahle', 33.8439, 35.9072);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lb', 'Amioun', 34.2994, 35.8097);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lb', 'Sidon', 33.5606, 35.3981);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lb', 'Beirut', 33.8869, 35.5131);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lk', 'Batticaloa', 7.717, 81.7);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lk', 'Colombo', 6.9167, 79.8333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lk', 'Kegalle', 7.2531, 80.3453);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lk', 'Hambantota', 6.1241, 81.1185);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lk', 'Matara', 5.949, 80.5428);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lk', 'Negombo', 7.2111, 79.8386);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lk', 'Sri Jayewardenepura Kotte', 6.9, 79.9164);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lk', 'Kandy', 7.297, 80.6385);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lk', 'Nuwara Eliya', 6.9667, 80.7667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lk', 'Moratuwa', 6.7804, 79.88);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lk', 'Anuradhapura', 8.335, 80.4108);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lk', 'Mullaittivu', 9.2833, 80.8);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lk', 'Jaffna', 9.6647, 80.0167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lk', 'Puttalam', 8.033, 79.826);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lk', 'Kurunegala', 7.4833, 80.3667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lk', 'Kilinochchi', 9.4004, 80.3999);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lk', 'Badulla', 6.9847, 81.0564);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lk', 'Galle', 6.0395, 80.2194);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lk', 'Ratnapura', 6.693, 80.386);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('lk', 'Trincomalee', 8.5667, 81.2333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mv', 'Un`goofaaru', 5.6681, 73.0302);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mv', 'Kudahuvadhoo', 2.6717, 72.8936);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mv', 'Felidhoo', 3.4718, 73.547);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mv', 'Dhihdhoo', 6.8874, 73.114);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mv', 'Funadhoo', 6.1509, 73.2901);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mv', 'Muli', 2.9217, 73.5811);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mv', 'Nilandhoo', 3.0567, 72.89);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mv', 'Thinadhoo', 0.5303, 72.9967);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mv', 'Male', 4.175, 73.5083);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mv', 'Thulusdhoo', 4.3742, 73.6517);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mv', 'Eydhafushi', 5.1038, 73.0699);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mv', 'Fonadhoo', 1.8342, 73.5031);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mv', 'Rasdhoo', 4.2631, 72.9919);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mv', 'Manadhoo', 5.7669, 73.4136);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mv', 'Naifaru', 5.4442, 73.3662);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mv', 'Veymandoo', 2.1878, 73.095);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mv', 'Viligili', 0.7539, 73.4353);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mv', 'Kulhudhuffushi', 6.6223, 73.0702);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mv', 'Mahibadhoo', 3.7571, 72.9689);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mv', 'Foammulah', -0.3, 73.4256);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mx', 'Tijuana', 32.525, -117.033);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mx', 'Guadalupe', 25.6775, -100.26);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mx', 'Aguascalientes', 21.876, -102.296);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mx', 'Puebla', 19.0333, -98.1833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mx', 'Nezahualcoyotl', 19.4, -98.9889);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mx', 'Ciudad Nezahualcoyotl', 19.41, -99.03);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mx', 'Reynosa', 26.0922, -98.2778);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mx', 'Saltillo', 25.4333, -101.0);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mx', 'Mexico City', 19.4333, -99.1333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mx', 'Chihuahua', 28.6353, -106.089);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mx', 'Hermosillo', 29.0989, -110.954);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mx', 'Culiacan', 24.8069, -107.394);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mx', 'Monterrey', 25.6667, -100.3);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mx', 'Ecatepec', 19.6097, -99.06);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mx', 'Durango', 24.0167, -104.667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mx', 'Naucalpan De Juarez', 19.4753, -99.2378);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mx', 'Mexicali', 32.6633, -115.468);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mx', 'Tlalnepantla', 19.5367, -99.1947);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mx', 'Toluca', 19.2925, -99.6569);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('mx', 'Juarez', 31.7386, -106.487);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('my', 'Bukit Mertajam', 5.3617, 100.461);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('my', 'Sandakan', 5.8388, 118.117);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('my', 'Sungai Petani', 5.65, 100.48);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('my', 'Ipoh', 4.6, 101.07);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('my', 'Alor Setar', 6.1167, 100.367);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('my', 'Tawau', 4.2981, 117.883);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('my', 'Bintulu', 3.17, 113.03);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('my', 'Kluang', 2.0383, 103.318);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('my', 'Klang', 3.0333, 101.45);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('my', 'Cukai', 4.2332, 103.448);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('my', 'George Town', 5.4145, 100.329);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('my', 'Muar', 2.05, 102.56);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('my', 'Melaka', 2.1889, 102.251);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('my', 'Teluk Intan', 4.0333, 101.017);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('my', 'Butterworth', 5.3942, 100.366);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('my', 'Kuala Terengganu', 5.3303, 103.141);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('my', 'Lahad Datu', 5.03, 118.34);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('my', 'Kuching', 1.5397, 110.354);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('my', 'Batu Pahat', 1.85, 102.93);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('my', 'Shah Alam', 3.0833, 101.533);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ng', 'Akure', 7.25, 5.195);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ng', 'Zaria', 11.0667, 7.7);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ng', 'Lagos', 6.45, 3.4);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ng', 'Owerri', 5.4833, 7.0333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ng', 'Enugu', 6.4403, 7.4942);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ng', 'Kano', 12.0, 8.5167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ng', 'Onitsha', 6.1667, 6.7833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ng', 'Ogbomoso', 8.1333, 4.25);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ng', 'Maiduguri', 11.8333, 13.15);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ng', 'Warri', 5.5167, 5.75);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ng', 'Yola', 9.2, 12.4833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ng', 'Calabar', 4.95, 8.325);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ng', 'Sokoto', 13.0622, 5.2339);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ng', 'Ilorin', 8.5, 4.55);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ng', 'Katsina', 12.9908, 7.6017);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ng', 'Kaduna', 10.5231, 7.4403);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ng', 'Ikare', 7.5304, 5.76);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ng', 'Abuja', 9.0556, 7.4914);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ng', 'Osogbo', 7.7667, 4.5667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ng', 'Port Harcourt', 4.75, 7.0);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('pk', 'Saidu Sharif', 34.75, 72.3572);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('pk', 'Jhang City', 31.2681, 72.3181);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('pk', 'Mardan', 34.1958, 72.0447);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('pk', 'Peshawar', 34.0, 71.5);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('pk', 'Shekhupura', 31.7083, 74.0);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('pk', 'New Mirpur', 33.1333, 73.75);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('pk', 'Mirpur Khas', 25.5269, 69.0111);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('pk', 'Multan', 30.1978, 71.4711);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('pk', 'Larkana', 27.56, 68.2264);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('pk', 'Sahiwal', 30.6706, 73.1064);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('pk', 'Dera Ghazi Khan', 30.05, 70.6333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('pk', 'Faisalabad', 31.418, 73.079);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('pk', 'Bahawalpur', 29.3956, 71.6722);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('pk', 'Sargodha', 32.0836, 72.6711);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('pk', 'Islamabad', 33.6989, 73.0369);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('pk', 'Chiniot', 31.7167, 72.9833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('pk', 'Nawabshah', 26.2442, 68.41);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('pk', 'Okara', 30.81, 73.4597);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('pk', 'Mingaora', 34.7717, 72.36);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('pk', 'Karachi', 24.86, 67.01);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('qa', 'Az Za`Ayin', 25.5774, 51.4831);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('qa', 'Ash Shihaniyah', 25.3709, 51.2226);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('qa', 'Doha', 25.3, 51.5333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('qa', 'Ar Rayyan', 25.2919, 51.4244);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('qa', 'Madinat Ash Shamal', 26.1293, 51.2009);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('qa', 'Al Khawr', 25.6839, 51.5058);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('qa', 'Al Wakrah', 25.18, 51.61);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('qa', 'Umm Salal `Ali', 25.4697, 51.3975);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ru', 'Krasnoyarsk', 56.0167, 92.8667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ru', 'Samara', 53.1833, 50.1167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ru', 'Volgograd', 48.7, 44.4833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ru', 'Khabarovsk', 48.4833, 135.067);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ru', 'Yekaterinburg', 56.8356, 60.6128);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ru', 'Kazan', 55.7908, 49.1144);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ru', 'Moscow', 55.7558, 37.6178);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ru', 'Tomsk', 56.4886, 84.9522);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ru', 'Tyumen', 57.15, 65.5333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ru', 'Irkutsk', 52.2833, 104.3);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ru', 'Rostov', 47.2333, 39.7167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ru', 'Orenburg', 51.7667, 55.1);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ru', 'Izhevsk', 56.85, 53.2167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ru', 'Makhachkala', 42.9833, 47.4833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ru', 'Ufa', 54.7333, 55.9667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ru', 'Yaroslavl', 57.6167, 39.85);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ru', 'Ulyanovsk', 54.3167, 48.3667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ru', 'Krasnodar', 45.0333, 38.9833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ru', 'Barnaul', 53.3567, 83.7872);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ru', 'Kemerovo', 55.3333, 86.0667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('se', 'Falun', 60.613, 15.647);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('se', 'Uppsala', 59.8601, 17.64);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('se', 'Molndal', 57.6542, 12.0139);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('se', 'Sundsvall', 62.4001, 17.3167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('se', 'Gavle', 60.667, 17.1666);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('se', 'Uppsala', 59.8498, 17.6389);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('se', 'Visby', 57.629, 18.3071);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('se', 'Kalmar', 56.6694, 16.3218);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('se', 'Helsingborg', 56.0424, 12.721);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('se', 'Gothenburg', 57.6717, 11.981);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('se', 'Huskvarna', 57.7919, 14.2756);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('se', 'Trollhattan', 58.2671, 12.3);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('se', 'Ostersund', 63.1833, 14.65);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('se', 'Linkoping', 58.4094, 15.6257);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('se', 'Vasteras', 59.6173, 16.5422);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('se', 'Vaxjo', 56.8837, 14.8167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('se', 'Stockholm', 59.3294, 18.0686);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('se', 'Borlange', 60.4833, 15.4167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('se', 'Norrkoping', 58.5954, 16.1787);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('se', 'Umea', 63.8285, 20.2706);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('sg', 'Singapore', 1.3, 103.8);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('so', 'Buur Gaabo', -1.2009, 41.852);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('so', 'Bu`aale', 1.0833, 42.5833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('so', 'Boorama', 9.9361, 43.1828);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('so', 'Laascaanood', 8.4774, 47.3597);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('so', 'Dhuusamarreeb', 5.5375, 46.3875);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('so', 'Baidoa', 3.1167, 43.65);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('so', 'Eyl', 7.9667, 49.85);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('so', 'Mogadishu', 2.0408, 45.3425);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('so', 'Kismaayo', -0.3603, 42.5489);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('so', 'Mereeg', 3.7666, 47.3);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('so', 'Caluula', 11.967, 50.75);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('so', 'Boosaaso', 11.28, 49.18);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('so', 'Garoowe', 8.4, 48.4833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('so', 'Hargeysa', 9.56, 44.065);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('so', 'Jamaame', 0.0722, 42.7506);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('so', 'Garbahaarrey', 3.35, 42.2667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('so', 'Hurdiyo', 10.5667, 51.1333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('so', 'Marka', 1.7156, 44.7703);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('so', 'Bandarbeyla', 9.4833, 50.8167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('so', 'Beledweyne', 4.736, 45.204);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('tv', 'Funafuti', -8.5167, 179.217);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ua', 'Rivne', 50.6197, 26.2514);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ua', 'Kherson', 46.6333, 32.6);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ua', 'Simferopol', 44.9484, 34.1);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ua', 'Chernivtsi', 48.2908, 25.9344);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ua', 'Ternopil', 49.5667, 25.6);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ua', 'Mariupol', 47.1306, 37.5639);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ua', 'Ivano-Frankivsk', 48.9228, 24.7106);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ua', 'Chernihiv', 51.5, 31.3);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ua', 'Zhytomyr', 50.2544, 28.6578);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ua', 'Zaporizhzhia', 47.8378, 35.1383);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ua', 'Dnipro', 48.45, 34.9833);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ua', 'Mykolaiv', 46.9667, 32.0);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ua', 'Sevastopol', 44.6, 33.5333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ua', 'Vinnytsia', 49.2372, 28.4672);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ua', 'Lviv', 49.8419, 24.0315);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ua', 'Donetsk', 48.0089, 37.8042);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ua', 'Kharkiv', 50.0, 36.2292);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ua', 'Sumy', 50.9068, 34.7992);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ua', 'Cherkasy', 49.4444, 32.0597);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('ua', 'Kyiv', 50.45, 30.5236);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('us', 'San Francisco', 37.7562, -122.443);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('us', 'San Jose', 37.3019, -121.849);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('us', 'Orlando', 28.4772, -81.3369);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('us', 'Dallas', 32.7936, -96.7662);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('us', 'Denver', 39.7621, -104.876);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('us', 'Miami', 25.7839, -80.2102);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('us', 'Philadelphia', 40.0077, -75.1339);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('us', 'Atlanta', 33.7627, -84.4224);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('us', 'Boston', 42.3188, -71.0846);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('us', 'Detroit', 42.3834, -83.1024);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('us', 'Queens', 40.7498, -73.7976);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('us', 'New York', 40.6943, -73.9249);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('us', 'Washington', 38.9047, -77.0163);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('us', 'Brooklyn', 40.6501, -73.9496);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('us', 'Minneapolis', 44.9635, -93.2678);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('us', 'Cleveland', 41.4767, -81.6804);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('us', 'Las Vegas', 36.2333, -115.265);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('us', 'Chicago', 41.8373, -87.6862);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('us', 'Phoenix', 33.5722, -112.089);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('us', 'San Antonio', 29.4658, -98.5253);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uy', 'Montevideo', -34.8667, -56.1667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uy', 'Las Piedras', -34.7167, -56.2167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uy', 'Tacuarembo', -31.71, -55.98);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uy', 'Canelones', -34.538, -56.284);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uy', 'Rosario', -34.3139, -57.3525);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uy', 'Colonia Del Sacramento', -34.4714, -57.8442);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uy', 'Santa Lucia', -34.4525, -56.3964);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uy', 'Ciudad De La Costa', -34.8167, -55.95);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uy', 'Maldonado', -34.9088, -54.9581);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uy', 'Treinta Y Tres', -33.2308, -54.3822);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uy', 'Salto', -31.3883, -57.9606);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uy', 'Carmelo', -33.9999, -58.2847);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uy', 'Rocha', -34.4833, -54.35);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uy', 'Mercedes', -33.25, -58.0319);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uy', 'Punta Del Este', -34.97, -54.95);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uy', 'San Jose', -34.3333, -56.7167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uy', 'Barros Blancos', -34.7542, -56.0042);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uy', 'Nueva Palmira', -33.87, -58.408);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uy', 'Durazno', -33.3833, -56.5167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uy', 'Minas', -34.3667, -55.2333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uz', 'Kattagan', 40.2, 64.9167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uz', 'Andijon', 40.7, 72.35);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uz', 'Xiva', 41.3783, 60.3639);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uz', 'Shahrisabz', 39.05, 66.8333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uz', 'Angren', 41.0167, 70.1333);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uz', 'Navoiy', 40.1, 65.3667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uz', 'Denov', 38.2772, 67.8872);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uz', 'Namangan', 40.9953, 71.6725);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uz', 'Termiz', 37.2242, 67.2783);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uz', 'Tashkent', 41.3, 69.2667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uz', 'Nukus', 42.4647, 59.6022);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uz', 'Olmaliq', 40.85, 69.6);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uz', 'Xo`Jayli Shahri', 42.4047, 59.4517);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uz', 'Marg`Ilon', 40.4667, 71.7167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uz', 'Samarkand', 39.6542, 66.9597);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uz', 'Jizzax', 40.1167, 67.85);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uz', 'Qo`Ng`Irot Shahri', 43.0758, 58.9067);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uz', 'Bekobod', 40.2258, 69.2292);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uz', 'Urganch', 41.5345, 60.6249);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('uz', 'Qarshi', 38.8667, 65.8);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('za', 'Benoni', -26.1883, 28.3206);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('za', 'Pretoria', -25.7464, 28.1881);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('za', 'George', -33.9667, 22.45);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('za', 'Durban', -29.8583, 31.025);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('za', 'Springs', -26.2547, 28.4428);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('za', 'Klerksdorp', -26.8667, 26.6667);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('za', 'Paarl', -33.7242, 18.9558);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('za', 'Potchefstroom', -26.715, 27.1033);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('za', 'Roodepoort', -26.1625, 27.8725);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('za', 'Johannesburg', -26.2044, 28.0416);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('za', 'Kimberley', -28.7386, 24.7586);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('za', 'Bloemfontein', -29.1, 26.2167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('za', 'Pietermaritzburg', -29.5833, 30.4167);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('za', 'Umtata', -31.58, 28.79);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('za', 'Welkom', -27.9831, 26.7208);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('za', 'Upington', -28.4572, 21.2425);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('za', 'Vryheid', -27.7694, 30.7914);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('za', 'Centurion', -25.8603, 28.1894);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('za', 'Port Elizabeth', -33.9581, 25.6);
INSERT INTO city_coordinates (country_name, city, latitude, longitude) VALUES ('za', 'Brits', -25.6167, 27.7667);

COMMIT;
